version: '3'

services:
  # the backend relational database for all data storage needs
  mysql:
    build: ./mysql/
    hostname: mysql
    container_name: mysql
    ports:
      - 3306:3306/tcp
    environment:
      TZ: "America/Denver"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql-bind/:/var/lib/mysql:rw
    restart: unless-stopped
  # a front-end web-ui for development via Jupyter notebooks
  jupyter:
    build: ./jupyter/
    hostname: jupyter
    container_name: jupyter
    ports:
      - 8888:8888/tcp
    environment:
      TZ: "America/Denver"
    volumes:
      - ./:/home/jovyan/work:rw
    restart: unless-stopped
  # an automation pipeline for continuously running data pulls
  automation:
    build: ./automation/
    hostname: automation
    container_name: automation
    environment:
      TZ: "America/Denver"
    volumes:
      - ./:/automation/:ro
    restart: unless-stopped